// <auto-generated />
using System;
using Gambling.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gambling.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20201207202738_ContestantVotes")]
    partial class ContestantVotes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Gambling.Models.Contestant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Offset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contestants");
                });

            modelBuilder.Entity("Gambling.Models.ContestantVotes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContestantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerID");

                    b.ToTable("ContestantVotes");
                });

            modelBuilder.Entity("Gambling.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesDrank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesLost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesWon")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Gambling.Models.ContestantVotes", b =>
                {
                    b.HasOne("Gambling.Models.Player", "Player")
                        .WithMany("ContestantVotes")
                        .HasForeignKey("PlayerID");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Gambling.Models.Player", b =>
                {
                    b.Navigation("ContestantVotes");
                });
#pragma warning restore 612, 618
        }
    }
}
